baseURL: "toiletcorp.github.io"
languageCode: "en-us"
title: "ToiletCorp"
theme: hugo-profile

Paginate: 1

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  title: "ToiletCorp"
  description: "The next big thing"
  # staticPath: ""  # The path to serve the static files from
  favicon: "./fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  menus:
    disableAbout: true
    disableExperience: true
    disableEducation: true
    disableProjects: true
    disableAchievements: true
    disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Big things are happening at"
    title: "ToiletCorp"
    subtitle: "Get in while you still can"
    content: ""
    image: /images/toiletcorp.png
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true 
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: Get in contact for insider information
    email: info@toiletcorp.us
    btnName: Email

